[package]
name = "cli"
version = "0.0.1"
edition = "2021"

[dependencies]
iggy = { path = "../iggy" }
anyhow = "1.0.70"
bytes = "1.4.0"
clap = { version = "4.1.11", features = ["derive"] }
figlet-rs = "0.1.5"
quinn = "0.10.0"
rcgen = "0.11.1"
rustls = { version = "0.21.1", features = ["dangerous_configuration", "quic"] }
tracing = { version = "0.1.37"}
tracing-subscriber = {version = "0.3.16"}
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["full"] }
tokio-rustls = "0.24.0"

[[bin]]
name = "iggy-cli"
path = "src/main.rs"
