[package]
name = "server"
version = "0.0.2"
edition = "2021"

[dependencies]
iggy = { path = "../iggy" }
streaming = { path = "../streaming" }
async-trait = "0.1.68"
axum = "0.6.20"
axum-server = { version = "0.5.1", features = ["tls-rustls", "tokio-rustls"] }
bytes = "1.4.0"
figlet-rs = "0.1.5"
figment = { version = "0.10.8", features = ["json", "toml", "env"] }
flume = "0.10.14"
thiserror = "1.0.40"
rustls-pemfile = "1.0.3"
serde = { version = "1.0.159", features = ["derive", "rc"] }
serde_json = "1.0.95"
tokio = { version = "1.28.2", features = ["full"] }
tokio-rustls = "0.24.0"
tokio-native-tls = "0.3.1"
tower = { version = "0.4.13" }
tower-http = { version = "0.4.0", features = [
    "add-extension",
    "cors",
    "trace",
] }
tower-layer = "0.3.2"
tower-service = "0.3.2"
clap = { version = "4.1.11", features = ["derive"] }
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3.16" }
chrono = "0.4.24"
anyhow = "1.0.70"
tokio-graceful-shutdown = "0.12.1"
rcgen = "0.11.1"
quinn = "0.10.0"
rustls = { version = "0.21.1", features = ["dangerous_configuration", "quic"] }

[dev-dependencies]
assert_cmd = "2.0.12"
predicates = "3.0.3"

[[bin]]
name = "iggy-server"
path = "src/main.rs"
